version: "2"
prepare:
  fetch:
    - url:  "https://raw.githubusercontent.com/runtastic/rt_rubocop_defaults/master/config/default.yml"
      path: .rt_rubocop_defaults.yml
plugins:
  git-legal:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-31-0
    config:
      file: .rubocop_codeclimate.yml
