inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

  - rt_rubocop_defaults

AllCops:
  TargetRubyVersion: 3.1
Layout/LineLength:
  Exclude:
    - 'sidekiq-undertaker.gemspec'
