require:
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rt_rubocop_defaults.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Layout/LineLength:
  Exclude:
    - 'sidekiq-undertaker.gemspec'
