require:
  - rubocop-rake
  - rubocop-rspec
  - rt_rubocop_defaults

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Exclude:
    - 'sidekiq-undertaker.gemspec'
