inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

require:
  - rt_rubocop_defaults

AllCops:
  TargetRubyVersion: 3.2
Layout/LineLength:
  Exclude:
    - 'sidekiq-undertaker.gemspec'
